---
title: "Working with messy genetic maps in R/qtl"
author: "JT Lovell"
date: "`r Sys.Date()`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
output: knitr:::html_vignette
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(qtl)
library(qtlTools)
```

```{r get qtlTools, eval = FALSE}
library(qtl)

library(devtools)
install_github("jtlovell/qtlTools")
library(qtlTools)
```

### Part 1: Make a map with some marker order and marker density problems and 
```{r make a messy map}
set.seed(42)
map<-sim.map(len = c(50,50,20,20), n.mar = c(25, 10, 10, 40), include.x=F)
plot(map)
cross0<-sim.cross(map, n.ind=50, type="f2",
          error.prob=0.001, missing.prob=0.001, map.function="kosambi")
plot.rf(cross0)

##########
jitterMarkerOrder<-function(cross, chr){
  mars<-1:nmar(cross)[chr]
  set.seed(42)
  badorder<-order(jitter(mars, factor = 10))
  cross<-switch.order(cross, chr = chr, order = badorder, 
                      error.prob=0.001, map.function="kosambi")
}
##########
cross1<-cross0
for(i in 1:nchr(cross1))   cross1<-jitterMarkerOrder(cross=cross1, chr = i)
plot.rf(cross1)

newmap<-est.map(cross1, error.prob=0.001, map.function="kosambi")
cross1 <- replace.map(cross1, newmap)
cross1<-est.rf(cross1)
```

### Part 2: Toss out markers that are not informative
```{r findSimilar markers}
cross2<-findSimilarMarkers(cross1, error.prob=0.001, map.function="kosambi", rf.threshold = 0.005)
plot.map(cross1, cross2, main = "comparison of full and culled maps")
```

### Part 3: Reorder markers iteratively
```{r repRipple markers}
cross3<-repRipple(cross2, error.prob=0.001, map.function="kosambi",window = 6)
plot.rf(cross2, main = "recombination fractions before ripple")
plot.rf(cross3, main = "recombination fractions after ripple")
```
