#' @title Using a QTL model, calcuate conditional QTL genotype effects
#'
#' @description
#' \code{calcQtlMeans} Takes a QTL model, formula
#'
#' @param cross The qtl cross object with marker names that need to be changed.
#' @param phe Character or numeric vector indicating the phenotype to be tested
#' @param mod A QTL model, generated by either makeqtl (etc.) or stepwiseqtl.
#' @param form If a generic (not stepwiseqtl) qtl model is supplied and does
#' not contain a formula, this is required. The formula must match the QTL in the
#' fitted QTL (mod) object.

#'
#' @details This function works for riself, bc, f2 and 4-way mapping populations. It is advisable
#' to run both sim.geno and calc.genoprob prior to using qtlStats, as this will speed up the analysis.
#' Also, it is important to note that this function works best on models generated from stepwiseqtl.
#'
#' @return A dataframe of statistics.
#'
#' @import qtl
#' @import lsmeans
#' @export
calcQtlMeans<-function(cross, mod, covar=NULL, phe, form, ... ){
  gp<-lapply(mod[[1]], function(x) apply(x,1, function(y) which(y==max(y))))
  geno.names<-colnames(mod[[1]][[1]])
  gp2<-data.frame(do.call(cbind,gp))
  colnames(gp2)<-mod$altname
  for(i in mod$altname) gp2[,i]<-as.factor(gp2[,i])
  phe.num<-pull.pheno(cross, pheno.col=phe)
  phe.num<-phe.num[!is.na(phe.num)]
  rownames(gp2)<-getid(cross)
  qtls<-mod$altname
  if(!is.null(covar)) {
    if(class(covar)=="data.frame") covar <- as.numeric(unlist(covar))
    covar<-as.factor(covar)
    addform<-as.formula(paste("y ~",paste(c(qtls,"covar"), collapse=" + ")))
  }else{
    addform<-as.formula(paste("y ~",paste(qtls, collapse=" + ")))
  }
  gp4<-cbind(gp2, covar = covar, y = as.vector(phe.num))
  lm.out<-lm(addform, data=data.frame(gp4))
  qtlns<-mod$name
  ls.out<-lapply(qtls, function(x) {
    l<-data.frame(geno =geno.names,  data.frame(summary(lsmeans(lm.out, x)))[,2:3])
    l<-lapply(geno.names, function(y){
      temp<-l[l$geno == y,2:3]
      colnames(temp)<-paste(colnames(temp),y,sep="_")
      return(temp)
    })
    l<-do.call(cbind,l)
    return(l)
    })
  out<-data.frame(qtlnames = qtlns, do.call(rbind, ls.out))
  return(out)
}
