#' @title Using a QTL model, calcuate conditional QTL genotype effects
#'
#' @description
#' \code{lsmeans4qtl} Takes a QTL model, formula and returns SAS - style LSMeans
#'
#' @param cross The qtl cross object with marker names that need to be changed.
#' @param phe Character or numeric vector indicating the phenotype to be tested
#' @param mod A QTL model, generated by either makeqtl (etc.) or stepwiseqtl.
#' @param form Character formula that must match the QTL in the fitted QTL (mod) object.
#' @param covar dataframe of covariates with names that match terms in the formula
#' @details This function iterates through the terms in the formula, pulling out lsmeans.
#' @return A dataframe of statistics.
#'
#' @import qtl
#' @import lsmeans
#' @export
lsmeans4qtl<-function(cross, phe, form, mod, covar){
  # 1. parse the formula
  form<-as.formula(form)
  terms<-attr(terms(form), "term.labels")
  # 2. infer the genotype for each individual at each qtl
  gp<-lapply(mod[[1]], function(x) apply(x,1, function(y) colnames(x)[which(y==max(y))]))
  names(gp)<-mod$altname
  gp<-data.frame(do.call(cbind,gp))
  # 3. add in phenotype and covariate data
  gp$y<-pull.pheno(cross, pheno.col=phe)
  gp<-data.frame(gp, covar)
  # 4. calculate lsmeans for each term in model
  lm.out<-lm(form,gp)
  out<-lapply(terms, function(x){
    lsmeans(lm.out, as.formula(paste("~",x,sep = "")))
  })
  # 5. reformat output so that it can be combined into a dataframe
  out<-lapply(out, function(x){
    x<-data.frame(summary(x))
    addterms<-terms[-grep(":",terms, fixed=T)]
    naterms<-addterms[!addterms %in% colnames(x)]
    for(i in naterms) x[,i]<-NA
    x<-x[,c(addterms,"lsmean", "SE", "df", "lower.CL","upper.CL")]
  })
  # 6. combine into data.frame and return
  out<-do.call(rbind, out)
  return(out)
}
